### ISSUE TITLE
[Phase 1] Ordering parts

### ISSUE THREAD

**Issue by Lechtob** [Lechtob/ThermoBee_Lite#11]
**Description:**

Ordering all necessary components according to the BOM.

**Subtasks:**

- [ ] Checking the availability of the selected components
- [ ] Ordering components from distributors (e.g. Mouser, Digi-Key)
- [ ] Find alternatives for unavailable components
