### ISSUE TITLE
[Phase 1] Validation and review of the schematics

### ISSUE THREAD

**Issue by Lechtob** [Lechtob/ThermoBee_Lite#6]
**Description:**

Review and validate the schematics for accuracy and completeness.

**Subtasks:**

- [ ] Electrical Rule Checks (ERC)
- [ ] Review the schematics
- [ ] Simulate if possible
