### ISSUE TITLE
[Phase 1] Creation of the PCB-Layout

### ISSUE THREAD

**Issue by Lechtob** [Lechtob/ThermoBee_Lite#7]
**Description:**

Draw the first iteration of the PCB-Layout for the ThermoBee Lite project, including the microcontroller, sensors, power supply, and programming interface.

**Subtasks:**

- [ ] Placing the components
- [ ] Routing of the connections
- [ ] Designing of the PCB-Antenna
- [ ] Drawing the outlines and silkscreen
- [ ] Placing mounting holes
