### ISSUE TITLE
[Phase 1] Validation and optimization of the PCB-Layout

### ISSUE THREAD

**Issue by Lechtob** [Lechtob/ThermoBee_Lite#8]
**Description:**

Execution of DRC and optimization of PCB layout.

**Subtasks:**

- [ ] RF-Antenna optimization
- [ ] Routing optimization
- [ ] Component placement optimization
- [ ] Design Rule Check (DRC)
