### ISSUE TITLE
[Phase 1] Creation of production documents

### ISSUE THREAD

**Issue by Lechtob** [Lechtob/ThermoBee_Lite#9]
**Description:**

Generation of all necessary files for PCB manufacturing.

**Subtasks:**

- [ ] Generating the Gerber-Files
- [ ] Generating the Drill-File
- [ ] Generating the Drill-Map-File
- [ ] Generating the BOM
- [ ] Generating the PaP-File
- [ ] Review all files

**Links:**

https://jlcpcb.com/help/article/how-to-generate-gerber-and-drill-files-in-kicad-8
